/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.RowSorterEvent;
import javax.swing.event.RowSorterListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Alejandro
 */
public class PanelAutomata extends javax.swing.JPanel {

    private Controlador controlador;
    private JButton estadoActual;
    private JButton estadoSiguiente;
    private JButton simbolo;
    private Color colorFondoBotones;
    /**
     * Creates new form PanelEstados
     */
    public PanelAutomata() {
        initComponents();
        controlador = Controlador.getInstance();
        actualizarEstadosInicales();
        actualizarEstadosAceptacion();
        crearTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jp_estadoss = new javax.swing.JPanel();
        jp_estadoss1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pn_estado_aceptacion = new javax.swing.JPanel();
        jp_estadoss2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pn_estado_inicial = new javax.swing.JPanel();
        pn_contenedor_tabla_transiciones = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Automata");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));
        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jp_estadoss.setBackground(new java.awt.Color(255, 255, 255));
        jp_estadoss.setAlignmentX(5.0F);
        jp_estadoss.setAlignmentY(5.0F);
        jp_estadoss.setAutoscrolls(true);
        jp_estadoss.setLayout(new java.awt.GridLayout(2, 1));

        jp_estadoss1.setBackground(new java.awt.Color(255, 255, 255));
        jp_estadoss1.setAlignmentX(5.0F);
        jp_estadoss1.setAlignmentY(5.0F);
        jp_estadoss1.setAutoscrolls(true);
        jp_estadoss1.setLayout(new java.awt.GridLayout(3, 1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Estado de Aceptacion");
        jp_estadoss1.add(jLabel5);

        pn_estado_aceptacion.setBackground(new java.awt.Color(255, 255, 255));
        pn_estado_aceptacion.setLayout(new java.awt.GridLayout(1, 0));
        jp_estadoss1.add(pn_estado_aceptacion);

        jp_estadoss.add(jp_estadoss1);

        jp_estadoss2.setBackground(new java.awt.Color(255, 255, 255));
        jp_estadoss2.setAlignmentX(5.0F);
        jp_estadoss2.setAlignmentY(5.0F);
        jp_estadoss2.setAutoscrolls(true);
        jp_estadoss2.setLayout(new java.awt.GridLayout(3, 1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Estado Inicial");
        jp_estadoss2.add(jLabel6);

        pn_estado_inicial.setBackground(new java.awt.Color(255, 255, 255));
        pn_estado_inicial.setLayout(new java.awt.GridLayout(1, 0));
        jp_estadoss2.add(pn_estado_inicial);

        jp_estadoss.add(jp_estadoss2);

        jPanel2.add(jp_estadoss, java.awt.BorderLayout.CENTER);

        add(jPanel2);

        pn_contenedor_tabla_transiciones.setBackground(new java.awt.Color(255, 255, 255));
        pn_contenedor_tabla_transiciones.setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        pn_contenedor_tabla_transiciones.add(jPanel1);

        add(pn_contenedor_tabla_transiciones);
    }// </editor-fold>//GEN-END:initComponents

     private void actualizarEstadosInicales() {
        ArrayList<String> estados = controlador.obtenerEstadosInicial();
        pn_estado_inicial.removeAll();
        pn_estado_inicial.revalidate();
        
        if(estados != null)
        {
            pn_estado_inicial.setLayout(new GridLayout(estados.size(),1));
            for (int i = 0 ; i< estados.size(); i++) {
                String key = estados.get(i);
                JButton btn = new JButton(key);
                pn_estado_inicial.add(btn);
            } 
        }   
    }
     private void actualizarEstadosAceptacion() {
        ArrayList<String> estados = controlador.obtenerEstadosAceptacion();
        pn_estado_aceptacion.removeAll();
        pn_estado_aceptacion.revalidate();
        
        if(estados != null)
        {
            pn_estado_aceptacion.setLayout(new GridLayout(estados.size(),1));
            for (int i = 0 ; i< estados.size(); i++) {
                String key = estados.get(i);
                JButton btn = new JButton(key);
                pn_estado_aceptacion.add(btn);
            } 
        } 
    }
    
     
    private void crearTabla()
    {
        pn_contenedor_tabla_transiciones.removeAll();
        pn_contenedor_tabla_transiciones.revalidate();
        
        HashMap<String,Integer> estados = controlador.obtenerEstados();
        HashMap<String,Integer> simbolos = controlador.obtenerSimbolos();
        Object[] StrSimbolos = new Object[simbolos.size()+1];
        StrSimbolos[0] = "";      
        for (Map.Entry<String, Integer> entry : simbolos.entrySet()) {
            String key = entry.getKey();
            Integer value = entry.getValue();
            StrSimbolos[value+1] = key;
        }
        
        Object[][] mat = controlador.obtenerTransiciones();
        if (mat != null)
        {
            JTable table = new JTable(mat, StrSimbolos);
            pn_contenedor_tabla_transiciones.add(table);
        }
        //DefaultTableModel model = new DefaultTableModel(StrSimbolos,estados.size());
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jp_estadoss;
    private javax.swing.JPanel jp_estadoss1;
    private javax.swing.JPanel jp_estadoss2;
    private javax.swing.JPanel pn_contenedor_tabla_transiciones;
    private javax.swing.JPanel pn_estado_aceptacion;
    private javax.swing.JPanel pn_estado_inicial;
    // End of variables declaration//GEN-END:variables
}
