/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;

/**
 *
 * @author Alejandro
 */
public class PanelIdentificar extends javax.swing.JPanel {

    private Controlador controlador;
    /**
     * Creates new form PanelEstados
     */
    public PanelIdentificar() {
        initComponents();
        controlador = Controlador.getInstance();
        lb_respuesta.setText(controlador.identificar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lb_respuesta = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("El Automata es:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        lb_respuesta.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lb_respuesta.setForeground(new java.awt.Color(0, 204, 51));
        lb_respuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(lb_respuesta);

        jPanel2.add(jPanel5);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lb_respuesta;
    // End of variables declaration//GEN-END:variables
}
