/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Modelo.AutomataFinito;
import controlador.Controlador;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;

/**
 *
 * @author Alejandro
 */
public class PanelReconocer extends javax.swing.JPanel {

    private Controlador controlador;
    /**
     * Creates new form PanelEstados
     */
    public PanelReconocer() {
        initComponents();
        controlador = Controlador.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jp_estados = new javax.swing.JPanel();
        tf_hilera = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lb_respuesta = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Por favor ingresar la hilera a reconocer");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1);

        tf_hilera.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_hilera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hileraActionPerformed(evt);
            }
        });

        jButton1.setText("Reconcer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_estadosLayout = new javax.swing.GroupLayout(jp_estados);
        jp_estados.setLayout(jp_estadosLayout);
        jp_estadosLayout.setHorizontalGroup(
            jp_estadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_estadosLayout.createSequentialGroup()
                .addGroup(jp_estadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_estadosLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(tf_hilera, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_estadosLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jp_estadosLayout.setVerticalGroup(
            jp_estadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_estadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_hilera, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jp_estados);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        lb_respuesta.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lb_respuesta.setForeground(new java.awt.Color(0, 204, 51));
        lb_respuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(lb_respuesta);

        jPanel2.add(jPanel5);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String hilera = tf_hilera.getText().toString();
        Boolean b = null;//reconocer aca se llama el metodo
        Controlador ctrl = Controlador.getInstance();
        AutomataFinito afAux = ctrl.obtenerAutomataFinito();
        
       // ctrl.convertirAF();
        b = ctrl.reconocer(hilera);
        if(b)
        {
            lb_respuesta.setText("ACEPTADA");
            lb_respuesta.setForeground(Color.GREEN);
        }
        else if(!b)
        {
            lb_respuesta.setText("RECHAZADA");
            lb_respuesta.setForeground(Color.red);
        }
        else
        {
            
        }
        ctrl.setAutomataFinito(afAux);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_hileraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hileraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_hileraActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jp_estados;
    private javax.swing.JLabel lb_respuesta;
    private javax.swing.JTextField tf_hilera;
    // End of variables declaration//GEN-END:variables
}
