/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.Controlador;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Alejandro
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private Controlador controlador;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();

        btn_vista_automata.setEnabled(false);
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 30));
        habilitarBotonesOpéraciones(false);
        btn_vista_simbolos.setEnabled(false);
        btn_vista_estado_incial.setEnabled(false);
        btn_vista_estado_acpetacion.setEnabled(false);
        btn_vista_transiciones.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jp_modificar_automata = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btn_vista_automata = new javax.swing.JButton();
        btn_vista_estados = new javax.swing.JButton();
        btn_vista_simbolos = new javax.swing.JButton();
        btn_vista_estado_incial = new javax.swing.JButton();
        btn_vista_estado_acpetacion = new javax.swing.JButton();
        btn_vista_transiciones = new javax.swing.JButton();
        jp_operaciones_automata = new javax.swing.JPanel();
        btn_abrir = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_identificar = new javax.swing.JButton();
        btn_reconocer = new javax.swing.JButton();
        btn_simplificar = new javax.swing.JButton();
        btn_convertir = new javax.swing.JButton();
        btn_union = new javax.swing.JButton();
        btn_interseccion = new javax.swing.JButton();
        jp_contenedor_principal = new javax.swing.JPanel();
        lb_tipo_automata = new javax.swing.JLabel();
        lb_tipo_automata1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(58, 171, 169));

        jp_modificar_automata.setBackground(new java.awt.Color(58, 171, 169));
        jp_modificar_automata.setLayout(new java.awt.GridLayout(7, 1));

        jPanel1.setBackground(new java.awt.Color(58, 171, 169));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("A");
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("B");
        jButton7.setBorder(null);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        jp_modificar_automata.add(jPanel1);

        btn_vista_automata.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista_automata.setText("Automata");
        btn_vista_automata.setBorder(null);
        btn_vista_automata.setContentAreaFilled(false);
        btn_vista_automata.setFocusPainted(false);
        btn_vista_automata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_vista_automataMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_vista_automataMouseReleased(evt);
            }
        });
        btn_vista_automata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vista_automataActionPerformed(evt);
            }
        });
        jp_modificar_automata.add(btn_vista_automata);

        btn_vista_estados.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista_estados.setText("Estados");
        btn_vista_estados.setBorder(null);
        btn_vista_estados.setContentAreaFilled(false);
        btn_vista_estados.setFocusPainted(false);
        btn_vista_estados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_vista_estadosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_vista_estadosMouseReleased(evt);
            }
        });
        btn_vista_estados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vista_estadosActionPerformed(evt);
            }
        });
        jp_modificar_automata.add(btn_vista_estados);

        btn_vista_simbolos.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista_simbolos.setText("Símbolos");
        btn_vista_simbolos.setBorder(null);
        btn_vista_simbolos.setContentAreaFilled(false);
        btn_vista_simbolos.setFocusPainted(false);
        btn_vista_simbolos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_vista_simbolosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_vista_simbolosMouseReleased(evt);
            }
        });
        btn_vista_simbolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vista_simbolosActionPerformed(evt);
            }
        });
        jp_modificar_automata.add(btn_vista_simbolos);

        btn_vista_estado_incial.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista_estado_incial.setText("Estado Inicial");
        btn_vista_estado_incial.setBorder(null);
        btn_vista_estado_incial.setContentAreaFilled(false);
        btn_vista_estado_incial.setFocusPainted(false);
        btn_vista_estado_incial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_vista_estado_incialMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_vista_estado_incialMouseReleased(evt);
            }
        });
        btn_vista_estado_incial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vista_estado_incialActionPerformed(evt);
            }
        });
        jp_modificar_automata.add(btn_vista_estado_incial);

        btn_vista_estado_acpetacion.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista_estado_acpetacion.setText("Estado Aceptación");
        btn_vista_estado_acpetacion.setBorder(null);
        btn_vista_estado_acpetacion.setContentAreaFilled(false);
        btn_vista_estado_acpetacion.setFocusPainted(false);
        btn_vista_estado_acpetacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_vista_estado_acpetacionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_vista_estado_acpetacionMouseReleased(evt);
            }
        });
        btn_vista_estado_acpetacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vista_estado_acpetacionActionPerformed(evt);
            }
        });
        jp_modificar_automata.add(btn_vista_estado_acpetacion);

        btn_vista_transiciones.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista_transiciones.setText("Transiciones");
        btn_vista_transiciones.setBorder(null);
        btn_vista_transiciones.setContentAreaFilled(false);
        btn_vista_transiciones.setFocusPainted(false);
        btn_vista_transiciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_vista_transicionesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_vista_transicionesMouseReleased(evt);
            }
        });
        btn_vista_transiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vista_transicionesActionPerformed(evt);
            }
        });
        jp_modificar_automata.add(btn_vista_transiciones);

        jp_operaciones_automata.setBackground(new java.awt.Color(58, 171, 169));
        jp_operaciones_automata.setLayout(new java.awt.GridLayout(1, 6));

        btn_abrir.setForeground(new java.awt.Color(255, 255, 255));
        btn_abrir.setText("Abrir");
        btn_abrir.setToolTipText("Abrir Automata");
        btn_abrir.setBorder(null);
        btn_abrir.setBorderPainted(false);
        btn_abrir.setContentAreaFilled(false);
        btn_abrir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_abrir.setFocusPainted(false);
        btn_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrirActionPerformed(evt);
            }
        });
        jp_operaciones_automata.add(btn_abrir);

        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setText("Guardar");
        btn_guardar.setToolTipText("Guardar Automata");
        btn_guardar.setBorder(null);
        btn_guardar.setBorderPainted(false);
        btn_guardar.setContentAreaFilled(false);
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guardar.setFocusPainted(false);
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jp_operaciones_automata.add(btn_guardar);

        btn_identificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_identificar.setText("Identificar");
        btn_identificar.setToolTipText("Identificar que tipo es el AF");
        btn_identificar.setBorder(null);
        btn_identificar.setContentAreaFilled(false);
        btn_identificar.setFocusPainted(false);
        btn_identificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_identificarActionPerformed(evt);
            }
        });
        jp_operaciones_automata.add(btn_identificar);

        btn_reconocer.setForeground(new java.awt.Color(255, 255, 255));
        btn_reconocer.setText("Reconocer");
        btn_reconocer.setToolTipText("Reconocer una hilera");
        btn_reconocer.setBorder(null);
        btn_reconocer.setContentAreaFilled(false);
        btn_reconocer.setFocusPainted(false);
        btn_reconocer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reconocerActionPerformed(evt);
            }
        });
        jp_operaciones_automata.add(btn_reconocer);

        btn_simplificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_simplificar.setText("Simplificar");
        btn_simplificar.setBorder(null);
        btn_simplificar.setContentAreaFilled(false);
        btn_simplificar.setFocusPainted(false);
        btn_simplificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simplificarActionPerformed(evt);
            }
        });
        jp_operaciones_automata.add(btn_simplificar);

        btn_convertir.setForeground(new java.awt.Color(255, 255, 255));
        btn_convertir.setText("Convertir");
        btn_convertir.setBorder(null);
        btn_convertir.setContentAreaFilled(false);
        btn_convertir.setFocusPainted(false);
        btn_convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_convertirActionPerformed(evt);
            }
        });
        jp_operaciones_automata.add(btn_convertir);

        btn_union.setForeground(new java.awt.Color(255, 255, 255));
        btn_union.setText("Union");
        btn_union.setBorder(null);
        btn_union.setContentAreaFilled(false);
        btn_union.setFocusPainted(false);
        btn_union.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_unionActionPerformed(evt);
            }
        });
        jp_operaciones_automata.add(btn_union);

        btn_interseccion.setForeground(new java.awt.Color(255, 255, 255));
        btn_interseccion.setText("Intersección");
        btn_interseccion.setBorder(null);
        btn_interseccion.setContentAreaFilled(false);
        btn_interseccion.setFocusPainted(false);
        btn_interseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_interseccionActionPerformed(evt);
            }
        });
        jp_operaciones_automata.add(btn_interseccion);

        jp_contenedor_principal.setBackground(new java.awt.Color(255, 255, 255));
        jp_contenedor_principal.setLayout(new java.awt.CardLayout());

        lb_tipo_automata.setBackground(new java.awt.Color(255, 255, 255));
        lb_tipo_automata.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_tipo_automata.setForeground(new java.awt.Color(255, 255, 255));
        lb_tipo_automata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tipo_automata.setText("-");

        lb_tipo_automata1.setBackground(new java.awt.Color(255, 255, 255));
        lb_tipo_automata1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_tipo_automata1.setForeground(new java.awt.Color(255, 255, 255));
        lb_tipo_automata1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tipo_automata1.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_tipo_automata, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_tipo_automata1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jp_modificar_automata, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jp_contenedor_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jp_operaciones_automata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jp_operaciones_automata, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp_contenedor_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_tipo_automata, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_tipo_automata1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jp_modificar_automata, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);

        jMenu1.setText("Archivo");

        jMenuItem2.setText("Nuevo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Guardar");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_vista_estadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vista_estadosActionPerformed
        PanelEstados panelEstados = new PanelEstados();
        mostrarPanel(jp_contenedor_principal, panelEstados);
        btn_vista_simbolos.setEnabled(true);
    }//GEN-LAST:event_btn_vista_estadosActionPerformed

    private void btn_vista_simbolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vista_simbolosActionPerformed
        PanelSimbolos panelSimbolos = new PanelSimbolos();
        mostrarPanel(jp_contenedor_principal, panelSimbolos);
       btn_vista_estado_incial.setEnabled(true);
    }//GEN-LAST:event_btn_vista_simbolosActionPerformed

    private void btn_vista_estado_incialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vista_estado_incialActionPerformed
        PanelEstadoInicial panelEstadoInicial = new PanelEstadoInicial();
        mostrarPanel(jp_contenedor_principal, panelEstadoInicial);
        btn_vista_estado_acpetacion.setEnabled(true);
    }//GEN-LAST:event_btn_vista_estado_incialActionPerformed

    private void btn_vista_estado_acpetacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vista_estado_acpetacionActionPerformed
        PanelEstadoAceptacion panelEstadoAceptacion = new PanelEstadoAceptacion();
        mostrarPanel(jp_contenedor_principal, panelEstadoAceptacion);
        btn_vista_transiciones.setEnabled(true);
    }//GEN-LAST:event_btn_vista_estado_acpetacionActionPerformed

    private void btn_vista_transicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vista_transicionesActionPerformed
        PanelTransiciones panelTransiciones = new PanelTransiciones();
        mostrarPanel(jp_contenedor_principal, panelTransiciones);
        btn_vista_automata.setEnabled(true);
    }//GEN-LAST:event_btn_vista_transicionesActionPerformed

    private void btn_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrirActionPerformed
        String texto = abrirArchivo();
        if (texto != null) {
            controlador = Controlador.getInstance();
            controlador.construirAtomata(texto);
            PanelAutomata panelAutomata = new PanelAutomata();
            mostrarPanel(jp_contenedor_principal, panelAutomata);
            btn_vista_automata.setEnabled(true);
            habilitarBotonesOpéraciones(true);
            String tipoA = controlador.identificarA();
            String tipoB = controlador.identificarB();
            lb_tipo_automata.setText(tipoA);
            lb_tipo_automata1.setText(tipoB);
            
            btn_vista_estado_acpetacion.setEnabled(true);
            btn_vista_estado_incial.setEnabled(true);
            btn_vista_simbolos.setEnabled(true);
            btn_vista_transiciones.setEnabled(true);
        }
        
    }//GEN-LAST:event_btn_abrirActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        controlador = Controlador.getInstance();
        String automata = controlador.obtenerAutomata();
        guardarArchivo(automata);
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_vista_automataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vista_automataActionPerformed
        PanelAutomata panelAutomata = new PanelAutomata();
        mostrarPanel(jp_contenedor_principal, panelAutomata);
    }//GEN-LAST:event_btn_vista_automataActionPerformed

    private void btn_convertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_convertirActionPerformed

        Controlador ctrl = Controlador.getInstance();
        ctrl.convertirAF();
        PanelAutomata panelAutomata = new PanelAutomata();
        mostrarPanel(jp_contenedor_principal, panelAutomata);
    }//GEN-LAST:event_btn_convertirActionPerformed

    private void btn_reconocerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reconocerActionPerformed

        PanelReconocer panelReconocer = new PanelReconocer();
        mostrarPanel(jp_contenedor_principal, panelReconocer);
    }//GEN-LAST:event_btn_reconocerActionPerformed

    private void btn_identificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_identificarActionPerformed
        PanelIdentificar panelIdentificar = new PanelIdentificar();
        mostrarPanel(jp_contenedor_principal, panelIdentificar);
    }//GEN-LAST:event_btn_identificarActionPerformed

    private void btn_simplificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simplificarActionPerformed
        // TODO add your handling code here:
        Controlador ctrl = Controlador.getInstance();
        ctrl.simplificar();
        PanelAutomata panelAutomata = new PanelAutomata();
        mostrarPanel(jp_contenedor_principal, panelAutomata);
    }//GEN-LAST:event_btn_simplificarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Controlador controlador = Controlador.getInstance();
        controlador.seleccionarAfA();
        if(controlador.getAutomataFinitoA() == null)
        {
            habilitarBotonesOpéraciones(false);
        }
        else
        {
            habilitarBotonesOpéraciones(true);
        }
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 11));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 30));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void habilitarBotonesOpéraciones(boolean b)
    {
         btn_guardar.setEnabled(b);
            btn_identificar.setEnabled(b);
            btn_reconocer.setEnabled(b);
            btn_simplificar.setEnabled(b);
            btn_convertir.setEnabled(b);
    }
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Controlador controlador = Controlador.getInstance();
        controlador.seleccionarAfB();
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 11));
        jButton7.setFont(new java.awt.Font("Tahoma", 1,30));
        if(controlador.getAutomataFinitoB() == null)
        {
            habilitarBotonesOpéraciones(false);
        }
        else
        {
            habilitarBotonesOpéraciones(true);
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        controlador = Controlador.getInstance();
        controlador.reiniciarVariables();
        jp_contenedor_principal.removeAll();
        jp_contenedor_principal.revalidate();
        btn_vista_automata.setEnabled(false);
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 30));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 11));
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btn_unionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_unionActionPerformed
        Controlador controlador = Controlador.getInstance();
        if(controlador.unirAutomatas())
        {
             JOptionPane.showMessageDialog(rootPane, "El Automata A fue reemplazado por el automata Unido");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "No se pudo unir los automatas "
                    + "revisar que esten construidos correctamente");
        }
    }//GEN-LAST:event_btn_unionActionPerformed

    private void btn_interseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_interseccionActionPerformed
        Controlador controlador = Controlador.getInstance();
        if(controlador.intersectar())
        {
             JOptionPane.showMessageDialog(rootPane, "El Automata A fue reemplazado por la interseccion del automata");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "No se pudo realizar la intersección de los automatas "
                    + "revisar que esten construidos correctamente");
        }
    }//GEN-LAST:event_btn_interseccionActionPerformed

    private void btn_vista_estadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista_estadosMousePressed
        btn_vista_estados.setFont(new java.awt.Font("Tahoma", 1, 18));
    }//GEN-LAST:event_btn_vista_estadosMousePressed

    private void btn_vista_estadosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista_estadosMouseReleased
        btn_vista_estados.setFont(new java.awt.Font("Tahoma", 0, 11));
    }//GEN-LAST:event_btn_vista_estadosMouseReleased

    private void btn_vista_automataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista_automataMousePressed
        btn_vista_automata.setFont(new java.awt.Font("Tahoma", 1, 18));
    }//GEN-LAST:event_btn_vista_automataMousePressed

    private void btn_vista_automataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista_automataMouseReleased
        btn_vista_automata.setFont(new java.awt.Font("Tahoma", 0, 11));
    }//GEN-LAST:event_btn_vista_automataMouseReleased

    private void btn_vista_simbolosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista_simbolosMousePressed
        btn_vista_simbolos.setFont(new java.awt.Font("Tahoma", 1, 18));
    }//GEN-LAST:event_btn_vista_simbolosMousePressed

    private void btn_vista_simbolosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista_simbolosMouseReleased
        btn_vista_simbolos.setFont(new java.awt.Font("Tahoma", 0, 11));
    }//GEN-LAST:event_btn_vista_simbolosMouseReleased

    private void btn_vista_estado_incialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista_estado_incialMousePressed
        btn_vista_estado_incial.setFont(new java.awt.Font("Tahoma", 1, 18));
    }//GEN-LAST:event_btn_vista_estado_incialMousePressed

    private void btn_vista_estado_incialMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista_estado_incialMouseReleased
        // TODO add your handling code here:
        btn_vista_estado_incial.setFont(new java.awt.Font("Tahoma", 0, 11));
    }//GEN-LAST:event_btn_vista_estado_incialMouseReleased

    private void btn_vista_estado_acpetacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista_estado_acpetacionMousePressed
        btn_vista_estado_acpetacion.setFont(new java.awt.Font("Tahoma", 1, 18));
    }//GEN-LAST:event_btn_vista_estado_acpetacionMousePressed

    private void btn_vista_estado_acpetacionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista_estado_acpetacionMouseReleased
        // TODO add your handling code here:
        btn_vista_estado_acpetacion.setFont(new java.awt.Font("Tahoma", 0, 11));
    }//GEN-LAST:event_btn_vista_estado_acpetacionMouseReleased

    private void btn_vista_transicionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista_transicionesMousePressed
        btn_vista_transiciones.setFont(new java.awt.Font("Tahoma", 1, 18));
    }//GEN-LAST:event_btn_vista_transicionesMousePressed

    private void btn_vista_transicionesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista_transicionesMouseReleased
        // TODO add your handling code here:
        btn_vista_transiciones.setFont(new java.awt.Font("Tahoma", 0, 11));
    }//GEN-LAST:event_btn_vista_transicionesMouseReleased

    /**
     * metodo que sobrescribe el contendio de un panel para hacer las vistas
     * dinamicas
     *
     * @param contenedor contenedor al que se le inyecta el nuevo panel
     * @param nuevoPanel panel a insertar
     */
    private void mostrarPanel(JPanel contenedor, JPanel nuevoPanel) {
        contenedor.removeAll();
        contenedor.revalidate();
        contenedor.add(nuevoPanel);
        nuevoPanel.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    private String abrirArchivo() {
        String aux = "";
        String texto = "";
        try {
            /**
             * llamamos el metodo que permite cargar la ventana
             */
            JFileChooser file = new JFileChooser();
            file.showOpenDialog(this);
            /**
             * abrimos el archivo seleccionado
             */
            File abre = file.getSelectedFile();

            /**
             * recorremos el archivo, lo leemos para plasmarlo en el area de texto
             */
            if (abre != null) {
                FileReader archivos = new FileReader(abre);
                BufferedReader lee = new BufferedReader(archivos);
                while ((aux = lee.readLine()) != null) {
                    texto += aux + "\n";
                }
                lee.close();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex + ""
                    + "\nNo se ha encontrado el archivo",
                    "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
        }
        return texto;//El texto se almacena en el JTextArea
    }

    private void guardarArchivo(String areaDeTexto) {
        try {
            String nombre = "";
            JFileChooser file = new JFileChooser();
            file.showSaveDialog(this);
            File guarda = file.getSelectedFile();

            if (guarda != null) {
                /*guardamos el archivo y le damos el formato directamente,
           * si queremos que se guarde en formato doc lo definimos como .doc*/
                FileWriter save = new FileWriter(guarda + ".txt");
                save.write(areaDeTexto);
                save.close();
                JOptionPane.showMessageDialog(null,
                        "El archivo se a guardado Exitosamente",
                        "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,
                    "Su archivo no se ha guardado",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_abrir;
    private javax.swing.JButton btn_convertir;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_identificar;
    private javax.swing.JButton btn_interseccion;
    private javax.swing.JButton btn_reconocer;
    private javax.swing.JButton btn_simplificar;
    private javax.swing.JButton btn_union;
    private javax.swing.JButton btn_vista_automata;
    private javax.swing.JButton btn_vista_estado_acpetacion;
    private javax.swing.JButton btn_vista_estado_incial;
    private javax.swing.JButton btn_vista_estados;
    private javax.swing.JButton btn_vista_simbolos;
    private javax.swing.JButton btn_vista_transiciones;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jp_contenedor_principal;
    private javax.swing.JPanel jp_modificar_automata;
    private javax.swing.JPanel jp_operaciones_automata;
    private javax.swing.JLabel lb_tipo_automata;
    private javax.swing.JLabel lb_tipo_automata1;
    // End of variables declaration//GEN-END:variables

}
